dbt_taxfix:
  target: airflow
  outputs:
    airflow:
      type: duckdb
      path: "{{ env_var('TAXFIX_DB_PATH', 'dbs/duckdb_data/taxfix.duckdb') }}"
      threads: 4
    dev:
      type: duckdb
      path: "{{ env_var('TAXFIX_DB_PATH', 'dbs/duckdb_data/taxfix.duckdb') }}"
      threads: 4
